# Generated by Django 3.2.15 on 2022-09-24 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option4',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option5',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option6',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option7',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='option8',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question2',
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('is_complete', models.BooleanField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.question'),
        ),
    ]
