# Generated by Django 3.2.15 on 2022-09-25 16:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_quiz_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='score',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
